version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/catcasts
    depends_on:
      - db
    command:
      mix phx.server
  db:
    image: "postgres"
    volumes:
     - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
